[env:esp32doit-devkit-v1]
platform = espressif32@6.10.0
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; Give it the 3MB partition space
board_build.partitions = huge_app.csv

; THE MAGIC FIX: Replace the standard ESP32 core with the Bluepad32 custom core
platform_packages = 
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

; Only fetch Firebase and Servo (Bluepad32 is now baked into the core above)
lib_deps = 
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 
    madhephaestus/ESP32Servo 
    links2004/WebSockets